import { Match, NormalizedEvent } from '@/types';
import { PdfReportLanguage } from '@/components/dashboards/PdfLanguageModal';

export interface ReportTranslations {
  title: string;
  subtitle: string;
  officialMatchReport: string;
  coverPageTitle: string;
  technicalMatchAnalysis: string;
  matchScore: string;
  competition: string;
  season: string;
  round: string;
  date: string;
  status: string;
  homeTeam: string;
  awayTeam: string;
  tacticalLineups: string;
  matchOverview: string;
  eventBreakdown: string;
  actionsTotal: string;
  descriptors: string;
  outcome: string;
  success: string;
  failed: string;
  goal: string;
  page: string;
  of: string;
  generatedBy: string;
  clubName: string;
  categoryNames: Record<string, string>;
  matchday: string;
  actionsRegistered: string;
  actionsShort: string;
  comparativeEventAnalysis: string;
  totalActionsOf: string;
  tacticalMapOf: string;
  actionPoints: string;
  locationDistribution: string;
  noSpecificDescriptors: string;
  starters: string;
  substitutes: string;
  formation: string;
  vs: string;
  progressLoadingLibs: string;
  progressCapturing: string;
  progressProcessingPage: string;
  progressDownloading: string;
}

export const TRANSLATIONS: Record<PdfReportLanguage, ReportTranslations> = {
  es: {
    title: 'INFORME TÉCNICO DE PARTIDO',
    subtitle: 'Análisis Táctico Post-Partido • Modelo Normalizado de Eventos',
    officialMatchReport: 'REPORTE OFICIAL DEL CUERPO TÉCNICO',
    coverPageTitle: 'Shabab Al Ordon Club • Análisis Táctico',
    technicalMatchAnalysis: 'Informe de Rendimiento & Campogramas Tácticos',
    matchScore: 'Resultado Final',
    competition: 'Competición',
    season: 'Temporada',
    round: 'Jornada',
    date: 'Fecha',
    status: 'Estado',
    homeTeam: 'Equipo Local',
    awayTeam: 'Equipo Visitante',
    tacticalLineups: 'Alineaciones Tácticas & Disposición Inicial',
    matchOverview: 'Resumen General del Partido',
    eventBreakdown: 'Desglose Comparativo por Evento Táctico',
    actionsTotal: 'Acciones Totales',
    descriptors: 'Descriptores',
    outcome: 'Resultado',
    success: 'Éxito',
    failed: 'Fallido',
    goal: 'Gol',
    page: 'Página',
    of: 'de',
    generatedBy: 'Generado por Antigravity Tactical Engine',
    clubName: 'Shabab Al Ordon Club',
    categoryNames: {
      salidas: 'Salidas de Balón',
      remates: 'Remates a Portería',
      faltas: 'Faltas & Balón Parado',
      transicion_defensiva: 'Transición Defensiva',
      pases: 'Pases & Construcción',
      centros: 'Centros al Área',
      recuperaciones: 'Recuperaciones',
      perdidas: 'Pérdidas',
    },
    matchday: 'Jornada',
    actionsRegistered: 'Acciones registradas',
    actionsShort: 'acc.',
    comparativeEventAnalysis: 'Análisis Comparativo de Evento',
    totalActionsOf: 'Acciones Totales',
    tacticalMapOf: 'Mapa Táctico',
    actionPoints: 'Puntos de Acción',
    locationDistribution: 'Ubicación y Distribución Registrada',
    noSpecificDescriptors: 'Sin descriptores específicos',
    starters: 'Titulares',
    substitutes: 'Suplentes',
    formation: 'Formación',
    vs: 'vs',
    progressLoadingLibs: 'Cargando librerías de capturas PDF...',
    progressCapturing: 'Capturando imágenes de alta definición...',
    progressProcessingPage: 'Procesando página',
    progressDownloading: 'Descargando archivo PDF...',
  },
  en: {
    title: 'TECHNICAL MATCH REPORT',
    subtitle: 'Post-Match Tactical Analysis • Normalized Event Model',
    officialMatchReport: 'TECHNICAL STAFF OFFICIAL REPORT',
    coverPageTitle: 'Shabab Al Ordon Club • Tactical Analysis',
    technicalMatchAnalysis: 'Performance Report & Tactical Pitch Maps',
    matchScore: 'Final Score',
    competition: 'Competition',
    season: 'Season',
    round: 'Matchday / Round',
    date: 'Date',
    status: 'Status',
    homeTeam: 'Home Team',
    awayTeam: 'Away Team',
    tacticalLineups: 'Tactical Lineups & Starting Formations',
    matchOverview: 'Match Overview',
    eventBreakdown: 'Comparative Event Breakdown & Pitch Maps',
    actionsTotal: 'Total Actions',
    descriptors: 'Descriptors',
    outcome: 'Outcome',
    success: 'Success',
    failed: 'Failed',
    goal: 'Goal',
    page: 'Page',
    of: 'of',
    generatedBy: 'Generated by Antigravity Tactical Engine',
    clubName: 'Shabab Al Ordon Club',
    categoryNames: {
      salidas: 'Build-up / Outlets',
      remates: 'Shots on Target',
      faltas: 'Fouls & Set Pieces',
      transicion_defensiva: 'Defensive Transition',
      pases: 'Passes & Build-up',
      centros: 'Crosses into Area',
      recuperaciones: 'Recoveries',
      perdidas: 'Possession Loss',
    },
    matchday: 'Matchday',
    actionsRegistered: 'Actions registered',
    actionsShort: 'act.',
    comparativeEventAnalysis: 'Comparative Event Analysis',
    totalActionsOf: 'Total Actions',
    tacticalMapOf: 'Tactical Map',
    actionPoints: 'Action Points',
    locationDistribution: 'Recorded Location & Distribution',
    noSpecificDescriptors: 'No specific descriptors',
    starters: 'Starting XI',
    substitutes: 'Substitutes',
    formation: 'Formation',
    vs: 'vs',
    progressLoadingLibs: 'Loading PDF capture libraries...',
    progressCapturing: 'Capturing high-definition images...',
    progressProcessingPage: 'Processing page',
    progressDownloading: 'Downloading PDF file...',
  },
  ar: {
    title: 'التقرير الفني الرسمي للمباراة',
    subtitle: 'التحليل التكتيكي لما بعد المباراة • نموذج الفعاليات الموحد',
    officialMatchReport: 'التقرير الرسمي للجهاز الفني والتحليلي',
    coverPageTitle: 'نادي شباب الأردن • التحليل التكتيكي',
    technicalMatchAnalysis: 'تقرير الأداء والخرائط التكتيكية للملعب',
    matchScore: 'النتيجة النهائية',
    competition: 'البطولة',
    season: 'الموسم',
    round: 'الجولة / المرحلة',
    date: 'التاريخ',
    status: 'الحالة',
    homeTeam: 'الفريق المستضيف',
    awayTeam: 'الفريق الضيف',
    tacticalLineups: 'التشكيلات التكتيكية والرسم البياني',
    matchOverview: 'الملخص العام للمباراة',
    eventBreakdown: 'التحليل المقارن لكل حدث تكتيكي',
    actionsTotal: 'إجمالي الفعاليات',
    descriptors: 'المؤشرات / الوصف',
    outcome: 'النتيجة',
    success: 'ناجح',
    failed: 'غير ناجح',
    goal: 'هدف',
    page: 'صفحة',
    of: 'من',
    generatedBy: 'تم إنشاؤه بواسطة محرك التحليل التكتيكي',
    clubName: 'نادي شباب الأردن',
    categoryNames: {
      salidas: 'الخروج بالكرة',
      remates: 'التسديدات على المرمى',
      faltas: 'الأخطاء والكرات الثابتة',
      transicion_defensiva: 'التحول الدفاعي',
      pases: 'التمريرات والبناء',
      centros: 'الكرات العرضية',
      recuperaciones: 'استعادة الكرة',
      perdidas: 'فقدان الكرة',
    },
    matchday: 'الجولة',
    actionsRegistered: 'الفعاليات المسجلة',
    actionsShort: 'فعالية',
    comparativeEventAnalysis: 'التحليل المقارن للحدث',
    totalActionsOf: 'إجمالي الفعاليات',
    tacticalMapOf: 'الخريطة التكتيكية',
    actionPoints: 'نقاط الفعالية',
    locationDistribution: 'الموقع والتوزيع المسجل',
    noSpecificDescriptors: 'لا توجد مؤشرات محددة',
    starters: 'التشكيلة الأساسية',
    substitutes: 'البدلاء',
    formation: 'التشكيل',
    vs: 'ضد',
    progressLoadingLibs: 'جارٍ تحميل مكتبات تصدير PDF...',
    progressCapturing: 'جارٍ التقاط صور عالية الدقة...',
    progressProcessingPage: 'جارٍ معالجة الصفحة',
    progressDownloading: 'جارٍ تنزيل ملف PDF...',
  },
};

export interface PdfDashboardCaptures {
  summaryCanvas: HTMLCanvasElement | null;
  categoryCaptures: { name: string; canvas: HTMLCanvasElement }[];
}

/**
 * Main Direct PDF Export function (No browser print window!).
 * Page 1 is a designed, fully-translated cover page. Every following page is a
 * literal screenshot (real DOM captured via html2canvas by the caller) of what
 * the user actually sees on the live dashboard, so the report matches the app
 * pixel for pixel instead of a redrawn mockup.
 */
export async function downloadPdfTechnicalReport(
  match: Match,
  events: NormalizedEvent[],
  lang: PdfReportLanguage = 'es',
  onProgress?: (msg: string) => void,
  captures?: PdfDashboardCaptures
): Promise<void> {
  if (typeof window === 'undefined') return;

  const t = TRANSLATIONS[lang] || TRANSLATIONS.es;
  const isRtl = lang === 'ar';
  const directionAttr = isRtl ? 'rtl' : 'ltr';

  onProgress?.(t.progressLoadingLibs);
  const html2canvas = (await import('html2canvas-pro')).default;
  const { jsPDF } = await import('jspdf');

  const homeTeam = match.home_team || 'Equipo Local';
  const awayTeam = match.away_team || 'Equipo Visitante';
  const homeScore = match.home_score ?? 0;
  const awayScore = match.away_score ?? 0;

  // Hidden Offscreen DOM Container used only to render & capture the cover page.
  const container = document.createElement('div');
  container.id = 'pdf-export-render-root';
  container.setAttribute('dir', directionAttr);
  container.style.position = 'fixed';
  container.style.top = '0';
  container.style.left = '-9999px';
  container.style.width = '1920px';
  container.style.backgroundColor = '#020617';
  container.style.fontFamily = 'system-ui, -apple-system, sans-serif';
  container.style.zIndex = '-9999';
  document.body.appendChild(container);

  const pageBoxClass = `w-[1920px] h-[1080px] bg-slate-950 text-slate-100 p-12 flex flex-col justify-between border-4 border-slate-800 shadow-2xl relative overflow-hidden box-border`;

  // ─────────────────────────────────────────────────────────
  // PAGE 1: PORTADA (COVER PAGE) — designed & fully translated
  // ─────────────────────────────────────────────────────────
  container.innerHTML = `
    <div class="${pageBoxClass}" style="background: radial-gradient(circle at 50% 30%, #0f172a 0%, #020617 100%);">
      <!-- Top Header -->
      <div class="flex items-center justify-between border-b-2 border-slate-800 pb-6">
        <div class="flex items-center gap-4">
          <div class="w-14 h-14 rounded-2xl bg-amber-500/20 border-2 border-amber-400 flex items-center justify-center text-amber-300 font-extrabold text-2xl shadow-lg">
            🇯🇴
          </div>
          <div>
            <h1 class="text-3xl font-black text-white tracking-wider uppercase">${t.clubName}</h1>
            <p class="text-sm font-bold text-amber-400 tracking-widest uppercase mt-0.5">${t.officialMatchReport}</p>
          </div>
        </div>
        <div class="text-right">
          <span class="px-4 py-1.5 rounded-full bg-slate-900 border border-slate-700 text-xs font-mono font-bold text-slate-300">
            ${t.title}
          </span>
          <p class="text-xs text-slate-400 font-mono mt-1">${new Date().toLocaleDateString(lang)}</p>
        </div>
      </div>

      <!-- Main Match Score Broadcast Card -->
      <div class="my-auto bg-slate-900/90 border-2 border-slate-800 rounded-3xl p-10 shadow-2xl backdrop-blur-xl flex flex-col items-center justify-center space-y-8">
        <span class="px-6 py-2 rounded-full bg-emerald-500/10 border border-emerald-500/40 text-emerald-400 text-sm font-mono font-black tracking-widest uppercase">
          ${t.technicalMatchAnalysis}
        </span>

        <div class="flex items-center justify-between w-full max-w-5xl px-8">
          <!-- Home Team -->
          <div class="flex flex-col items-center space-y-4 flex-1 text-center">
            ${
              match.home_team_logo
                ? `<img src="${match.home_team_logo}" class="w-32 h-32 object-contain drop-shadow-2xl" />`
                : `<div class="w-32 h-32 rounded-3xl bg-slate-800 border-2 border-slate-700 flex items-center justify-center text-4xl font-black text-amber-400">${homeTeam.substring(0, 2).toUpperCase()}</div>`
            }
            <h2 class="text-3xl font-black text-white tracking-tight">${homeTeam}</h2>
            <span class="text-xs font-bold text-slate-400 uppercase tracking-widest">${t.homeTeam}</span>
          </div>

          <!-- Score Box -->
          <div class="px-10 py-6 rounded-3xl bg-slate-950 border-2 border-amber-400/50 shadow-2xl text-center flex flex-col items-center justify-center shrink-0">
            <div class="text-6xl font-mono font-black text-white tracking-wider flex items-center gap-4">
              <span>${homeScore}</span>
              <span class="text-amber-400 text-4xl">-</span>
              <span>${awayScore}</span>
            </div>
            <span class="text-xs font-mono font-bold text-slate-400 mt-2 uppercase tracking-widest">${t.matchScore}</span>
          </div>

          <!-- Away Team -->
          <div class="flex flex-col items-center space-y-4 flex-1 text-center">
            ${
              match.away_team_logo
                ? `<img src="${match.away_team_logo}" class="w-32 h-32 object-contain drop-shadow-2xl" />`
                : `<div class="w-32 h-32 rounded-3xl bg-slate-800 border-2 border-slate-700 flex items-center justify-center text-4xl font-black text-cyan-400">${awayTeam.substring(0, 2).toUpperCase()}</div>`
            }
            <h2 class="text-3xl font-black text-white tracking-tight">${awayTeam}</h2>
            <span class="text-xs font-bold text-slate-400 uppercase tracking-widest">${t.awayTeam}</span>
          </div>
        </div>

        <!-- Match Info Grid -->
        <div class="grid grid-cols-4 gap-6 w-full max-w-5xl border-t border-slate-800/80 pt-8 font-mono text-center">
          <div class="bg-slate-950 p-4 rounded-2xl border border-slate-800">
            <span class="text-[11px] font-bold text-slate-500 uppercase block">${t.competition}</span>
            <span class="text-sm font-extrabold text-slate-200 mt-1 block truncate">${match.competition || 'Jordan Pro League'}</span>
          </div>
          <div class="bg-slate-950 p-4 rounded-2xl border border-slate-800">
            <span class="text-[11px] font-bold text-slate-500 uppercase block">${t.round}</span>
            <span class="text-sm font-extrabold text-amber-400 mt-1 block">${t.matchday} ${match.round || 1}</span>
          </div>
          <div class="bg-slate-950 p-4 rounded-2xl border border-slate-800">
            <span class="text-[11px] font-bold text-slate-500 uppercase block">${t.date}</span>
            <span class="text-sm font-extrabold text-slate-200 mt-1 block">${match.date || '2026-09-04'}</span>
          </div>
          <div class="bg-slate-950 p-4 rounded-2xl border border-slate-800">
            <span class="text-[11px] font-bold text-slate-500 uppercase block">${t.actionsTotal}</span>
            <span class="text-sm font-extrabold text-emerald-400 mt-1 block">${events.length} ${t.actionsRegistered}</span>
          </div>
        </div>
      </div>

      <!-- Footer -->
      <div class="flex items-center justify-between border-t border-slate-800 pt-4 text-xs font-mono text-slate-500">
        <span>${t.generatedBy}</span>
        <span>${t.page} 1</span>
      </div>
    </div>
  `;

  onProgress?.(t.progressCapturing);

  const coverCanvas = await html2canvas(container.firstElementChild as HTMLElement, {
    scale: 1.5,
    useCORS: true,
    backgroundColor: '#020617',
    logging: false,
  });

  document.body.removeChild(container);

  // Initialize jsPDF (Landscape, 1920x1080 resolution)
  const pdf = new jsPDF({
    orientation: 'landscape',
    unit: 'px',
    format: [1920, 1080],
  });
  pdf.addImage(coverCanvas.toDataURL('image/jpeg', 0.95), 'JPEG', 0, 0, 1920, 1080);

  // ─────────────────────────────────────────────────────────
  // Composes a full 1920x1080 PDF page from a real captured screenshot canvas,
  // fitting it (contain) below a thin translated caption bar. Uses the browser's
  // own Canvas2D text rendering (not jsPDF's built-in fonts) so accented and
  // Arabic captions render correctly regardless of chosen language.
  // ─────────────────────────────────────────────────────────
  function composeScreenshotPage(canvas: HTMLCanvasElement, caption: string, pageNum: number): string | null {
    if (!canvas || canvas.width === 0 || canvas.height === 0) {
      console.warn('PDF export: skipping page with empty capture canvas', caption);
      return null;
    }
    const pageCanvas = document.createElement('canvas');
    pageCanvas.width = 1920;
    pageCanvas.height = 1080;
    const ctx = pageCanvas.getContext('2d') as CanvasRenderingContext2D;

    ctx.fillStyle = '#020617';
    ctx.fillRect(0, 0, 1920, 1080);

    // Caption bar
    ctx.fillStyle = '#0f172a';
    ctx.fillRect(0, 0, 1920, 74);
    ctx.textBaseline = 'middle';
    ctx.direction = isRtl ? 'rtl' : 'ltr';
    ctx.font = 'bold 30px system-ui, -apple-system, sans-serif';
    ctx.fillStyle = '#fbbf24';
    ctx.textAlign = isRtl ? 'right' : 'left';
    ctx.fillText(caption, isRtl ? 1880 : 40, 37);
    ctx.font = '18px system-ui, -apple-system, sans-serif';
    ctx.fillStyle = '#94a3b8';
    ctx.textAlign = isRtl ? 'left' : 'right';
    ctx.fillText(t.clubName, isRtl ? 40 : 1880, 37);

    // Fit the real screenshot (contain) into the remaining area
    const areaX = 24;
    const areaY = 94;
    const areaW = 1920 - areaX * 2;
    const areaH = 1080 - areaY - 46;
    const scale = Math.min(areaW / canvas.width, areaH / canvas.height);
    const w = canvas.width * scale;
    const h = canvas.height * scale;
    const x = areaX + (areaW - w) / 2;
    const y = areaY + (areaH - h) / 2;

    ctx.fillStyle = '#0f172a';
    ctx.fillRect(x - 4, y - 4, w + 8, h + 8);
    ctx.drawImage(canvas, x, y, w, h);

    // Footer
    ctx.font = '16px system-ui, -apple-system, sans-serif';
    ctx.fillStyle = '#64748b';
    ctx.textAlign = isRtl ? 'right' : 'left';
    ctx.fillText(t.generatedBy, isRtl ? 1880 : 40, 1060);
    ctx.textAlign = isRtl ? 'left' : 'right';
    ctx.fillText(`${t.page} ${pageNum}`, isRtl ? 40 : 1880, 1060);

    try {
      return pageCanvas.toDataURL('image/jpeg', 0.92);
    } catch (err) {
      // A tainted canvas (cross-origin team logo without CORS headers) blocks
      // toDataURL entirely. Skip this page instead of aborting the whole export.
      console.warn('PDF export: could not encode page (likely a tainted canvas from a cross-origin image)', caption, err);
      return null;
    }
  }

  let pageNum = 2;
  const totalCapturePages = (captures?.summaryCanvas ? 1 : 0) + (captures?.categoryCaptures.length || 0);
  let processed = 0;
  let pagesAdded = 0;

  const addCapturedPage = (canvas: HTMLCanvasElement, caption: string) => {
    try {
      const dataUrl = composeScreenshotPage(canvas, caption, pageNum);
      if (!dataUrl) return;
      pdf.addPage([1920, 1080], 'landscape');
      pdf.addImage(dataUrl, 'JPEG', 0, 0, 1920, 1080);
      pageNum++;
      pagesAdded++;
    } catch (err) {
      // Never let one bad capture (tainted canvas, decoding error, etc.) abort the export.
      console.warn('PDF export: failed to add captured page, skipping it', caption, err);
    }
  };

  if (captures?.summaryCanvas) {
    processed++;
    onProgress?.(`${t.progressProcessingPage} ${processed} ${t.of} ${totalCapturePages}...`);
    addCapturedPage(captures.summaryCanvas, t.matchOverview);
  }

  for (const cap of captures?.categoryCaptures || []) {
    processed++;
    onProgress?.(`${t.progressProcessingPage} ${processed} ${t.of} ${totalCapturePages}...`);
    const label = t.categoryNames[cap.name] || cap.name;
    addCapturedPage(cap.canvas, label);
  }

  if (totalCapturePages > 0 && pagesAdded === 0) {
    console.warn('PDF export: all screenshot pages failed to encode; only the cover page was generated.');
  }

  onProgress?.(t.progressDownloading);
  const safeHome = homeTeam.replace(/[^a-zA-Z0-9]/g, '_');
  const safeAway = awayTeam.replace(/[^a-zA-Z0-9]/g, '_');
  const fileName = `Informe_Tecnico_${safeHome}_vs_${safeAway}_${lang}.pdf`;

  // Trigger DIRECT browser file download! (No print dialog!)
  pdf.save(fileName);
}
